- name: ICTSC6 Q4 common
  hosts: rabbit
  become: True
  tasks:
    - name: Install libselinux-python
      yum: name=libselinux-python state=latest

    - name: upgrade all packages
      yum: name=* state=latest

    - name: copy data file generator
      copy: >
        src=epel.repo
        dest=/etc/yum.repos.d/epel.repo
        owner=root
        mode=0755

    - name: Install parted
      yum: name=parted state=latest

    - name: Install other packages
      yum: name=python-pip state=latest
