---
- name: ICTSC6 Q9 slave
  hosts: slave
  become: True
  tasks:

    - name: copy my.cnf file
      copy: >
          src=my.cnf dest=/etc/my.cnf
          owner=root mode=0644
          seuser=system_u serole=object_r setype=mysqld_etc_t selevel=s0

    - name: restart MySQL
      service: name=mysqld state=restarted

    - name: mysql CHANGE MASTER
      mysql_replication: >
          login_user=root
          login_password=root
          master_host=192.168.5.5
          master_user=repl
          master_password=repl
          master_port=3306
          master_log_file=mysql-bin-log.000005
          master_log_pos=774
          mode=changemaster

    - name: mysql START SLAVE
      mysql_replication: >
          login_user=root
          login_password=root
          mode=startslave

    - name: restart mysqld
      service: name=mysqld state=restarted
