---
- name: ICTSC6 Q9 master
  hosts: rabbit
  become: True
  tasks:

    - name: create disk ( sparse disk )
      command: dd if=/dev/zero of=/data.img bs=1 count=1 seek=10G
      
    - name: unload loop mod
      command: rmmod loop --force

    - name: reload loop mod with option
      command: modprobe loop max_part=15

    - name: attach disk to loop
      command: losetup -f -P /data.img

    - name: create partition table GPT for disk mounted loop
      command: parted --script --align optimal /dev/loop0 -- mklabel gpt

    - name: create partition for disk mounted loop
      command: parted --script --align optimal /dev/loop0 -- mkpart linux ext4 1MiB 1GiB

    - name: detatch disk mounted loop
      command: losetup -d /dev/loop0

    - name: reattach disk
      commandL losetup -f -P /data.img

    - name: format partition for loop0p1
      command: mkfs.ext4 /dev/loop0p1 -i 3000000

    - name: mkdir /horse
      command: mkdir /horse

    - name: mount disk
      mount: name=/horse src=loop0p1 fstype=ext4 state=mounted

    - name: make data dir
      file: path=/horse/data state=directory owner=root group=root mode=0755

      

    - name: add repl user
      mysql_user: >
          login_user=root
          login_password=root
          name=repl
          password=repl
          priv="*.*:REPLICATION SLAVE"
          host="192.168.5.%"

    - name: insert user record
      shell: /usr/bin/mysql --user=root --password=root -e "INSERT INTO ictsc.user (id, name) VALUES (3, 'ictsc6666666666666666666666666666');"

    - name: restart mysqld
      service: name=mysqld state=restarted
