# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |v|
  v.vm.box = "kaorimatz/centos-6.8-x86_64"

  v.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vagrant_root = File.dirname(File.expand_path(__FILE__))
    disk2 = File.join(vagrant_root, 'disk2.vdi')
    vb.customize ['createhd', '--filename', disk2, '--size', 10 * 1024]
    vb.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk2]
  end

  v.ssh.insert_key = false

  v.vm.define "rabbit" do |r|
    r.vm.network "private_network", ip: "192.168.11.2"
    r.vm.provision "ansible" do |a|
      a.playbook = "../ansible/playbook.yml"
      a.limit = 'all'
    end
  end

#  v.vm.define "sla" do |sla|
#    sla.vm.network "private_network", ip: "192.168.11.3"
#    sla.vm.provision "ansible" do |run|
#      run.limit = 'all'
#      run.limit = 'all'
#      run.playbook = "../ansible/playbook.yml"
#      run.groups = {
#        "rabbit" => ["master"],
#        "sla" => ["slave"]
#      }
#    end
#  end

end
